CC = gcc

CFLAGS = -Wall -Werror -ansi -pedantic

CFLAGS += -D_XOPEN_SOURCE=500

CFLAGS += -g

REP = ripinpepporinism8icryeverytimeplsnocopypasterinogoodbyelolripinpepporinism8icryeverytimeplsnocopypasterinogoodbyelolripinpepporinism8icryeverytimeplsnocopypasterinogoodbyelolripinpepporinism8icryeverytimeplsnocopypasterinogoodbyelolripinpepporinism8icryeverytimeplsnocopypasterinogoodbyelol

all: prlimit maccess maccess+


%:%.c fatal.o
	$(CC) $(CFLAGS) fatal.o -o $@ $<

fatal.o:
	$(CC) $(CFLAGS) -c fatal.c


test:maccess+ loop 
	./maccess+ gdxwfhxdg.gdhjgdcgfdx -rv 
	./maccess+ ./$(REP)/$(REP)/$(REP)/$(REP)/$(REP)/$(REP)/$(REP)/$(REP)/$(REP)/$(REP)/$(REP)/$(REP)/$(REP)/$(REP)/$(REP)/$(REP)/troll.txt -wv
	./maccess+ self -rv
	./maccess+ maccess/maccess.c -rv
	./maccess+ Makefile -xv

loop:
	ln -s self self

clean:
	rm -f *~ *.o self prlimit maccess maccess+